//browse

export const animatedTVShows = [
  {
    title: "The Disastrous Life of Saiki K.",
    tone: ["Deadpan", "Comedy Anime"],
    img: "/saiki.jpeg",
    banner: "/saiki-banner.jpeg",
    genres: ["Shounen Anime", "Japanese Anime Series"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2018",
    rating: "TV-14",
    length: null,
    seasons: "3",
    language: "japanese",
    cast: ["Hiroshi Kamiya"],
    description:
      "A high school student with powerful psychic abilities tries to live an ordinary life by keeping his true nature a secret from his many quirky classmates and anyone else he comes across.",
  },
  {
    title: "Inside Job",
    tone: ["Witty", "Adult Cartoon"],
    img: "/inside-job.jpeg",
    banner: "/inside-job-banner.webp",
    genres: ["Adult Animation"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    language: "english",
    cast: ["Lizzie Caplan"],
    description:
      "Anti-social genius Reagan Ridley and her dysfunctional team work to hide the world's conspiracies.",
  },
  {
    title: "Bojack Horseman",
    tone: [],
    img: "/bojack-horseman.jpeg",
    banner: "/bojack-horseman-banner.webp",
    genres: ["Sitcom", "TV Comedies"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2020",
    rating: "TV-MA",
    length: null,
    seasons: "6",
    language: "english",
    cast: ["Will Arnett", "Aaron Paul"],
    description: "",
  },
  {
    title: "Disenchantment",
    img: "/disenchantment.jpeg",
    banner: "/disenchantment-banner.jpeg",
    genres: ["Adult Animation", "TV Comedies", "Fantasy TV Shows"],
    tone: ["Witty", "Irreverent"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "",
    length: null,
    seasons: "4",
    language: "english",
    cast: ["Abbi Jacobson", "Eric André", "Nat Faxon"],
    description:
      "It follows the misadventures of hard-drinking young princess Bean, her feisty elf companion Elfo and personal demon Luci. The oddball trio encounters the likes of ogres, sprites, imps, trolls and human fools along the way.",
  },
  {
    title: "Castlevania",
    img: "/castlevania.jpeg",
    banner: "/castlevania-banner.jpeg",
    genres: ["Action Anime", "Anime based on a Video Game", "Anime Series"],
    tone: ["Violent", "Scary"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2021",
    rating: "TV-MA",
    length: null,
    seasons: "4",
    language: "english",
    cast: ["Richard Armitage", "James Callis", "Alejandra Reynoso"],
    description:
      "As Dracula and his legion of vampires prepare to rid the world of humanity's stain, Trevor Belmont is no longer alone, and he and his misfit comrades race to find a way to save mankind from the grief-maddened Dracula.",
  },
  {
    title: "Dead End: Paranormal Park",
    img: "/dead-end.jpeg",
    banner: "/dead-end-banner.webp",
    genres: ["Kids' TV", "TV Comedies", "TV Cartoons"],
    tone: ["Quirky", "Heartfelt"],
    netflixOriginal: true,
    media: "show",
    year: "2022",
    rating: "TV-Y7",
    length: null,
    seasons: "2",
    language: "english",
    cast: ["Zach Barack", "Kody Kavitha", "Emily Osment"],
    description:
      "Two teenagers and a talking pug work together to fight demons in a haunted amusement park. The two slowly start to grow into themselves as they face zombies, game show hosts, witches, and crushes.",
  },
];

export const popularShows = [
  {
    title: "Wednesday",
    tone: [],
    img: "/wednesday.jpeg",
    banner: "/wednesday-banner.jpeg",
    genres: ["TV Mysteries", "Dark Comedy"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-14",
    length: null,
    seasons: "1",
    language: "english",
    cast: ["Jenna Ortega", "Gwendoline Christie", "Riki Lindhome"],
    description:
      "While attending Nevermore Academy, Wednesday Addams attempts to master her emerging psychic ability, thwart a killing spree and solve the mystery that embroiled her parents 25 years ago.",
  },
  {
    title: "Alice in Borderland",
    tone: ["Dystopian", "Dark"],
    img: "/alice-in-borderland.jpeg",
    banner: "/alice-in-borderland-banner.webp",
    genres: ["Action & Adventure"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "2",
    language: "japanese",
    cast: ["Kento Yamazaki"],
    description:
      "Obsessed gamer Arisu suddenly finds himself in a strange, emptied-out version of Tokyo in which he and his friends must compete in dangerous games in order to survive.",
  },
  {
    title: "First Kill",
    tone: ["soapy", "suspenseful"],
    img: "/first-kill.jpeg",
    banner: "/first-kill-banner.webp",
    genres: ["Romantic TV Dramas", "TV Dramas", "TV Shows Based on Books"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    language: "english",
    cast: ["Sarah Catherine Hook", "Imani Lewis"],
    description:
      "Falling in love is tricky for teens Juliette and Calliope because one's a vampire and the other's a vampire hunter -- and both are ready to make their first kill.",
  },
  {
    title: "On My Block",
    tone: ["Witty", "Emotional", "Teen"],
    img: "/on-my-block.jpeg",
    banner: "/on-my-block-banner.jpeg",
    genres: ["Romantic TV Dramas", "TV Dramas", "Teen TV Shows"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2021",
    rating: "TV-14",
    length: null,
    seasons: "14",
    language: "english",
    cast: ["Sierra Capri", "Jason Genao", "Brett Gray"],
    description:
      "Lifelong friendships are tested as Monse, Ruby, Jamal and Cesar confront the challenges of adolescence and life in their predominantly Hispanic and black neighborhood in South Central Los Angeles in this coming-of-age comedy series.",
  },
  {
    title: "Narcos",
    tone: [],
    img: "/narcos.jpeg",
    banner: "",
    genres: ["Gritty", "Dark", "Thriller"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2017",
    rating: "TV-MA",
    length: null,
    seasons: "3",
    language: "english",
    cast: ["Pedro Pascal", "Boyd Holbro"],
    description: "",
  },
  {
    title: "Control Z",
    tone: ["Soapy", "Teen", "Ensemble"],
    img: "/control-z.jpeg",
    banner: "/control-z-banner.jpeg",
    genres: ["Soapy", "Teen", "Ensemble"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "3",
    language: "spanish",
    cast: ["Ana Valeria Becerril", "Michael Ronda"],
    description: "",
  },

  {
    title: "Never Have I Ever",
    tone: [],
    img: "/never-have-i-ever.jpeg",
    banner: "/never-have-i-ever-banner.jpeg",
    genres: ["Quirky", "Feel-Good"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-14",
    length: null,
    seasons: "3",
    language: "english",
    cast: ["Maitreyi Ramakrishnan", "Poorna Jagannathan"],
    description: "",
  },
  {
    title: "The Umbrella Academy",
    genres: [],
    img: "/umbrella-academy.jpeg",
    banner: "/umbrella-academy-banner.jpeg",
    tone: ["Superhero", "Offbeat"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "3",
    language: "english",
    cast: ["Elliot Page", "Tom Hopper", "David Castañeda"],
    description: "",
  },
  {
    title: "Supernatural",
    genres: [],
    img: "/supernatural.jpeg",
    banner: "/supernatural-banner.webp",
    tone: ["Scary"],
    netflixOriginal: false,
    media: "show",
    episodes: null,
    year: "2019",
    rating: "TV-MA",
    length: null,
    seasons: "15",
    language: "english",
    cast: ["Jared Padalecki", "Jensen Ackles", "Mark Sheppard"],
    description: "",
  },
  {
    title: "Diablero",
    img: "/diablero.jpeg",
    banner: "/diablero-banner.jpg",
    genres: ["Mexican", "TV Shows Based on Books", "TV Thrillers"],
    tone: ["Scary", "Horror", "Irreverent"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2020",
    rating: "TV-MA",
    length: null,
    seasons: "2",
    language: "spanish",
    cast: [
      "Christopher Von Uckermann",
      "Horacio García Rojas",
      "Gisselle Kuri",
    ],
    description:
      "A young priest enlists the help of a demon hunter and a paranormal expert to search for a kidnapped girl in the underworld of Mexico City.",
  },
  {
    title: "Warrior Nun",
    img: "/warrior-nun.jpeg",
    banner: "/warrior-nun-banner.avif",
    genres: ["Teen TV Shows", "Fantasy TV Shows", "TV Shows Based on Comics"],
    tone: [],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "2",
    language: "english",
    cast: ["Alba Baptista", "Thekla Reuten", "Lorena Andrea"],
    description:
      "A young woman wakes up in a morgue with inexplicable powers and gets caught up in a battle between good and evil.",
  },
  {
    title: "The Haunting of Bly Manor",
    img: "/haunting-of-bly-manor.jpeg",
    banner: "/haunting-of-bly-manor-banner.jpeg",
    genres: ["TV Dramas", "TV Shows Based on Books", "TV Mysteries"],
    tone: ["Ominous", "Scary", "Dark"],
    netflixOriginal: true,
    media: "show",
    year: "2020",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    episodes: "9",
    language: "english",
    cast: ["Victoria Pedretti", "Oliver Jackson-Cohen", "Henry Thomas"],
    description:
      "A young governess arrives at Bly Manor and begins to see apparitions haunting the estate.",
  },
  {
    title: "The Witcher",
    img: "/the-witcher.jpeg",
    banner: "/the-witcher-banner.jpeg",
    genres: ["TV Dramas", "TV Shows Based on Books"],
    tone: ["Exciting"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2021",
    rating: "TV-MA",
    seasons: "2",
    language: "english",
    cast: ["Henry Cavill", "Anya Chalotra", "Freya Allan"],
    description:
      "The witcher Geralt, a mutated monster hunter, struggles to find his place in a world in which people often prove more wicked than beasts.",
  },
  {
    title: "You",
    img: "/you.jpeg",
    banner: "/you-banner.jpeg",
    genres: ["TV Dramas", "TV Shows Based on Books", "TV Thrillers"],
    tone: ["Dark"],
    netflixOriginal: true,
    media: "show",
    year: "2023",
    rating: "TV-MA",
    seasons: "4",
    length: null,
    episodes: null,
    language: "english",
    cast: ["Penn Badgley", "Victoria Pedretti", "Elizabeth Lail"],
    description:
      "What would you do for love? For Joe, an intense young man who frequently becomes smitten with beautiful, smart women, this question is put to the test.",
  },
];

export const koreanDramas = [
  {
    title: "The Glory",
    img: "/the-glory.jpeg",
    banner: "/the-glory-banner.webp",
    genres: ["TV Drama", "Thriller"],
    tone: ["Dark"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    language: "korean",
    cast: ["Song Hye-kyo", "Lim Ji-yeon", "Lee Do-hyun", "Jung Sung II"],
    description:
      "A young woman, bullied to the point of deciding to drop out of school, plans the best way to get revenge. After becoming a primary school teacher, she takes in the son of the man who tormented her the most to enact her vengeance.",
  },
  {
    title: "My Liberation Notes",
    tone: ["Understated"],
    img: "/my-liberation-notes.jpeg",
    banner: "/my-liberation-notes-banner.jpeg",
    genres: ["Korean", "TV Dramas"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    language: "korean",
    cast: ["Lee Min-ki", "Kim Ji-won", "Son Suk-ku"],
    description:
      "Three siblings, exhausted by the monotony of day-to-day adulthood, seek to find fulfillment and freedom from their humdrum lives.",
  },
  {
    title: "Little Women",
    img: "/little-women.jpeg",
    banner: "/little-women-banner.webp",
    genres: ["TV Dramas", "Korean", "TV Mysteries"],
    tone: ["Suspenseful", "Mystery", "Ensemble"],
    netflixOriginal: true,
    media: "show",
    year: "2022",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    episodes: "12",
    language: "korean",
    cast: ["Kim Go-eun", "Nam Ji-hyun", "Park Ji-hu"],
    description:
      "Sisters become embroiled in a major incident and face off against the wealthiest family in the nation.",
  },
  {
    title: "Move to Heaven",
    img: "/move-to-heaven.jpeg",
    banner: "/move-to-heaven-banner.jpeg",
    genres: ["TV Dramas", "Korean"],
    tone: ["Heartfelt", "Emotional"],
    netflixOriginal: true,
    media: "show",
    year: "2021",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    episodes: "10",
    language: "korean",
    cast: ["Lee Je-hoon", "Tang Jun-sang", "Hong Seung-hee"],
    description:
      "A young man with Asperger syndrome and his uncle work as trauma cleaners, clearing out the possessions of dead people, uncovering the stories they left behind and telling them to loved ones.",
  },
  {
    title: "Inspector Koo",
    img: "/inspector-koo.jpeg",
    banner: "/inspector-koo-banner.jpeg",
    genres: ["Korean", "TV Comedies", "Crime TV Shows"],
    tone: ["Suspenseful"],
    netflixOriginal: true,
    media: "show",
    year: "2021",
    rating: "TV-MA",
    length: null,
    seasons: "1",
    episodes: "12",
    language: "korean",
    cast: ["Lee Young-ae", "Kim Hye-jun", "Kim Hae-sook"],
    description:
      "A reclusive ex-cop reenters the game as an insurance investigator searching for clues in crime scenes perfectly staged by a serial killer.",
  },
  {
    title: "20th Century Girl",
    img: "/20th-century-girl.jpeg",
    banner: "/20th-century-girl-banner.jpeg",
    genres: ["Korean", "Dramas", "Romantic Movies"],
    tone: ["Charming", "Heartfelt"],
    netflixOriginal: true,
    media: "movie",
    year: "2022",
    rating: "TV-PG",
    length: "2h 1m",
    episodes: null,
    seasons: null,
    language: "korean",
    cast: ["Kim You-jung", "Byeon Woo-seok", "Park Jung-woo"],
    description:
      "A teen girl has her eyes set on a boy for her lovesick best friend. However, things become complicated when she falls in love and is forced to choose between love and friendship.",
  },
];

//shows
export const teenShows = [
  {
    title: "Derry Girls",
    img: "/derry-girls.jpeg",
    banner: "/derry-girls-banner.webp",
    genres: ["Sitcoms", "British", "Teen TV Shows"],
    tone: ["Witty", "Quirky"],
    netflixOriginal: true,
    media: "show",
    year: "2020",
    rating: "TV-MA",
    length: null,
    seasons: "3",
    episodes: null,
    language: "english",
    cast: ["Saoirse-Monica Jackson", "Nicola Coughlan", "Louisa Harland"],
    description:
      "Amidst the political conflict of nothern Ireland in the 1990s, five spirited students contend with the universal challenges of being a teenager.",
  },
  {
    title: "The Girl in the Mirror",
    img: "/the-girl-in-the-mirror.jpeg",
    banner: "/the-girl-in-the-mirror-banner.jpeg",
    genres: ["TV Dramas", "Spanish", "Teen TV Shows"],
    tone: ["Mind-Bending", "Suspenseful"],
    netflixOriginal: true,
    media: "show",
    year: "2022",
    rating: "TV-MA",
    seasons: "1",
    episodes: "9",
    length: null,
    language: "spanish",
    cast: ["Mireia Oriol", "Álex Villazán", "Pol Monen"],
    description:
      "After losing her memory in a bizarre accident that kills most of her classmates, Alma tries to unravel what happened that day and regain her identity.",
  },
  {
    title: "Chilling Adventures of Sabrina",
    tone: [],
    img: "/sabrina.jpeg",
    banner: "/sabrina-banner.webp",
    genres: ["Slick", "Chilling", "Horror"],
    netflixOriginal: true,
    media: "show",
    episodes: null,
    year: "2020",
    rating: "TV-14",
    length: null,
    seasons: "4",
    language: "english",
    cast: ["Kiernan Shipka", "Ross Lynch", "Miranda Otto"],
    description: "",
  },
  {
    title: "Red Rose",
    img: "/red-rose.jpeg",
    banner: "/red-rose-banner.jpeg",
    genres: ["TV Dramas", "British", "Teen TV Shows"],
    media: "show",
    year: "2023",
    rating: "TV-MA",
    seasons: "1",
    episodes: "8",
    language: "english",
    cast: ["Amelia Clarkson", "Isis Hainesworth", "Natalie Blair"],
    description:
      "An original horror series exploring the relationship between teenagers and their online lives. A sense of danger looms over the protagonists, and whether real or imagined, the dark web or something supernatural, with a story of friendship that emerges through the convention of classic horror.",
  },
];

//movies
export const popularMovies = [
  {
    title: "Unlocked",
    img: "/unlocked.jpeg",
    banner: null,
    genres: ["Korean", "Thriller Movies", "Mysteries"],
    tone: [],
    netflixOriginal: true,
    media: "movie",
    length: "1h 57m",
    episodes: null,
    seasons: null,
    year: "2022",
    rating: "TV-MA",
    language: "korean",
    cast: ["Chun Woo-hee", "Yim Si-wan", "Kim Hie-won"],
    description:
      "A woman's life is turned upside-down after a dangerous man gets a hold of her lost cell phone and uses it to track her every move.",
  },
  {
    title: "Kill Boksoon",
    img: "/kill-boksoon.jpeg",
    banner: "/kill-boksoon-banner.jpeg",
    genres: ["Korean", "Action & Adventure"],
    tone: ["Violent", "Suspenseful"],
    netflixOriginal: true,
    media: "movie",
    year: "2023",
    rating: "TV-MA",
    length: "2h 16m",
    episodes: null,
    seasons: null,
    language: "korean",
    cast: ["Jeon Do-yeon", "Sul Kyung-gu", "Kim Si-a"],
    description:
      "At work, she's a renowned assassin. At home, she's a single mum to a teenage girl. Killing is easy. It's parenting that's the hard part.",
  },
  {
    title: "Anonymously Yours",
    img: "/anonymously-yours.jpeg",
    banner: "/anonymously-yours-banner.jpeg",
    genres: ["Mexican", "Quirky Romance", "Dramas"],
    tone: ["Quirky", "Feel-Good", "Romantic"],
    netflixOriginal: true,
    media: "movie",
    year: "2021",
    rating: "TV-14",
    length: "1h 41m",
    episodes: null,
    seasons: null,
    language: "spanish",
    cast: ["Annie Cabello", "Ralf", "Estefi Merelles"],
    description:
      "After an accidental text message turns into a digital friendship, Vale and Alex start crushing on each other without realizing they've met in real life.",
  },
  {
    title: "Queen on the Run",
    img: "/queens-on-the-run.jpeg",
    genres: ["Mexican", "Comedies", "Action & Adventure"],
    tone: ["Irreverent", "Goofy"],
    netflixOriginal: true,
    media: "movie",
    year: "2023",
    rating: "TV-MA",
    length: "1h 37m",
    episodes: null,
    seasons: null,
    language: "spanish",
    cast: ["Martha Higareda", "Paola Núñez", "Alejandra Ambrosi"],
    description:
      "When four women finally take the road trip they planned in high school, they have no idea of the things they'll bump into, sometimes literally.",
  },
  {
    title: "Bullet Train",
    img: "/bullet-train.jpeg",
    genres: ["Comedies", "Movies Based on Books", "Action & Adventure"],
    tone: ["Offbeat"],
    netflixOriginal: false,
    media: "movie",
    year: "2022",
    rating: "R",
    length: "2h 6m",
    episodes: null,
    seasons: null,
    language: "english",
    cast: ["Brad Pitt", "Joey King", "Aaron Taylor-Johnson"],
    description:
      "Ladybug is an unlucky assassin who's determined to do his job peacefully after one too many gigs has gone off the rails. Fate, however, may have other plans as his latest mission puts him on a collision course with lethal adversaries from around the globe -- all with connected yet conflicting objectives -- on the world's fastest train.",
  },
  {
    title: "Furies",
    img: "/furies.jpeg",
    banner: "/furies-banner.webp",
    genres: ["Vietnamese", "Dramas", "Martial Arts Movies"],
    tone: ["Gritty", "Emotional"],
    netflixOriginal: true,
    media: "movie",
    year: "2023",
    rating: "TV-MA",
    length: "1h 50m",
    episodes: null,
    seasons: null,
    language: "vietnamese",
    cast: ["Dong Anh Quynh", "Toc Tien", "Thuan Nguyen"],
    description: "Three furious vigilantes unite to take down a sinister",
  },
  {
    title: "Enola Holmes 2",
    img: "/enola-holmes-2.jpeg",
    banner: "/enola-holmes-2-banner.jpeg",
    genres: ["Family Movies", "Dramas", "Mysteries"],
    tone: ["Witty", "Exciting"],
    netflixOriginal: true,
    media: "movie",
    year: "2022",
    rating: "PG-13",
    length: "2h 10m",
    episodes: null,
    seasons: null,
    language: "english",
    cast: ["Millie Bobby Brown", "Henry Cavill", "David Thewlis"],
    description:
      "Enola Holmes takes on her first case as a detective, but to unravel the mystery of a missing girl, she'll need some help from friends -- and brother Sherlock.",
  },
  {
    title: "20th Century Girl",
    img: "/20th-century-girl.jpeg",
    banner: "/20th-century-girl-banner.jpeg",
    genres: ["Korean", "Dramas", "Romantic Movies"],
    tone: ["Charming", "Heartfelt"],
    netflixOriginal: true,
    media: "movie",
    year: "2022",
    rating: "TV-PG",
    length: "2h 1m",
    episodes: null,
    seasons: null,
    language: "korean",
    cast: ["Kim You-jung", "Byeon Woo-seok", "Park Jung-woo"],
    description:
      "A teen girl has her eyes set on a boy for her lovesick best friend. However, things become complicated when she falls in love and is forced to choose between love and friendship.",
  },
];

export const familyMovies = [
  {
    title: "Enola Holmes 2",
    img: "/enola-holmes-2.jpeg",
    banner: "/enola-holmes-2-banner.jpeg",
    genres: ["Family Movies", "Dramas", "Mysteries"],
    tone: ["Witty", "Exciting"],
    netflixOriginal: true,
    media: "movie",
    year: "2022",
    rating: "PG-13",
    episodes: null,
    seasons: null,
    length: "2h 10m",
    language: "english",
    cast: ["Millie Bobby Brown", "Henry Cavill", "David Thewlis"],
    description:
      "Enola Holmes takes on her first case as a detective, but to unravel the mystery of a missing girl, she'll need some help from friends -- and brother Sherlock.",
  },
  {
    title: "20th Century Girl",
    img: "/20th-century-girl.jpeg",
    banner: "/20th-century-girl-banner.jpeg",
    genres: ["Korean", "Dramas", "Romantic Movies"],
    tone: ["Charming", "Heartfelt"],
    netflixOriginal: true,
    media: "movie",
    year: "2022",
    rating: "TV-PG",
    length: "2h 1m",
    episodes: null,
    seasons: null,
    language: "korean",
    cast: ["Kim You-jung", "Byeon Woo-seok", "Park Jung-woo"],
    description:
      "A teen girl has her eyes set on a boy for her lovesick best friend. However, things become complicated when she falls in love and is forced to choose between love and friendship.",
  },
  {
    title: "Over The Hedge",
    img: "/over-the-hedge.jpeg",
    banner: "/over-the-hedge-banner.jpeg",
    genres: ["Family Movies", "Kids & Family Movies", "Comedies"],
    tone: ["Kids", "Animal", "Comedy"],
    netflixOriginal: false,
    media: "",
    year: "",
    rating: "PG",
    length: "1h 23m",
    episodes: null,
    seasons: null,
    language: "english",
    cast: ["Bruce Willis", "Garry Shandling", "Steve Carell"],
    description:
      "When Verne (Araya A Hargate) and fellow woodland friends awake from winter's hibernation, they find they have some new neighbors: humans, and RJ (Chatchai Plengpanich), an opportunistic raccoon who shows the others how to exploit the suburban bounty laid out before them.",
  },

  {
    title: "Hotel Translyvania",
    img: "/hotel-translyvania.jpeg",
    banner: "/hotel-translyvania-banner.jpeg",
    genres: ["Family Movies", "Kids & Family Movies", "Comedies"],
    tone: ["Goofy", "Kids", "First Love"],
    netflixOriginal: false,
    media: "movie",
    year: "2012",
    rating: "PG",
    length: "1h 31m",
    episodes: null,
    seasons: null,
    language: "english",
    cast: ["Adam Sandler", "Andy Samberg", "Selena Gomez"],
    description:
      "Hotel Translyvania owner Dracula pulls double duty as an overprotective dad when an unwelcome suitor shows interest in his teenage daughter.",
  },
  {
    title: "Shrek Forever After: The Final Chapter",
    img: "/shrek-forever-after-final-chapter.jpeg",
    banner: "/shrek-banner.jpeg",
    genres: ["Family Movies", "Kids & Family Movies", "Comedies"],
    tone: ["Magical", "Kids"],
    netflixOriginal: false,
    media: "movie",
    year: "2010",
    rating: "PG",
    length: "1h 35m",
    episodes: null,
    seasons: null,
    language: "english",
    cast: ["Mike Myers", "Eddie Murphy", "Cameron Diaz"],
    description:
      "Duped into signing a contract with devious Rumpelstiltskin, he finds himself in an alternate version of Far Far Away, where ogres are hunted, Rumpelstiltskin rules, and he and Fiona (Cameron Diaz) have never met.",
  },
];
